# a = "!!!Avinash!!!!!! Avi"
# print(len(a))
# print(a)
# print(a.upper())
# print(a.lower())
# print(a.strip("!"))
# print(a.rstrip("!"))
# print(a.lstrip("!"))pr
# print(a.replace("Avinash", "avi"))
# print(a.split(" "))
blogheading = "Introduction"
# print(blogheading.capitalize())
# print(blogheading.center(50))
# print(blogheading.endswith("js."))
# print(blogheading.find(""))
# print(blogheading.index("o"))
# print(blogheading.isalnum())
# print(blogheading.isalpha())
# print(blogheading.is)
# print(blogheading.isprintable())
# print(blogheading.isspace())
# print(blogheading.istitle())
print(blogheading.startswith("n"))